# -*- coding: utf-8 -*-
"""TSR Protocol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SD4uHDGa08gpfbfuPkLYJij7vBiNpc7F
"""

# Commented out IPython magic to ensure Python compatibility.
clear;
# %This is the code when the exponential random variables are taken as 1 
count1=1;
h=1;
g=1;
i1=1;
j1=1;
for alpha = 0.0001 : 0.0001 : 0.9999
        Yd=(2*power(abs(h),4)*power(abs(g),2)*alpha)/(    (2*power(abs(h),2)*power(abs(g),2)*0.02*alpha)   + (power(abs(h),2)*0.02*(1-alpha))     +(0.02*0.02*(1-alpha))  );
        Yo=Yd+rand;
        R=log2(1+Yo);
        a=0.02*Yo*(1-alpha);
        b=0.02*0.02*Yo*(1-alpha);
        c=2*alpha;
        d=2*0.02*Yo*alpha;
        u=sqrt(4*a/c);
        Pout=1-((exp((-d/c))*u).*abs(besselk(1,u)));
        Throughput=(1-Pout)*(1-alpha)*R/2;
        arrayx(count1)=alpha;
        arrayy(count1)=abs(Throughput);
        count1=count1+1;
end
plot(arrayx,arrayy,'r');
hold on;
clear;
count1=1;
syms X a b c d Yo Yd ;
h=1;
g=1;
i1=1;
j1=1;
for alpha = 0.0001 : 0.0001 : 0.9999
        u=sqrt(4*(0.02*X*(1-alpha)/(2*alpha)));
        K1=abs(besselk(1,u));
        K0=abs(besselk(0,u));
        expr= ( (((u^2).*K0*exp(-(2*0.02*X*alpha)/(2*alpha)))./(2.*X)  )  +((2*0.02.*X*alpha)*u.*K1*exp(-(2*0.02.*X*alpha)/(2*alpha)))./((2*alpha).*X)).*(log2(1+X));
        expr1=matlabFunction(expr);
        C= integral(expr1,0,Inf);
        throughput = C * (1 - alpha ) /2 ;
        arrayx(count1) = alpha;
        arrayy(count1) = throughput;
        count1=count1+1;
       
end
plot(arrayx,arrayy,'b');
clear;

xlabel(' Variation of Alpha');
ylabel( ' Variation of Throughput , ');
title(' Variation of Throughput with respect to Alpha ')
legend({'Delay Limited Transmission','Delay Tolerant Transmission'},'Location','northeast')
grid on;